### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by AgrawalAmey** [FabianLauer/chrome-vs-code#1]
Is there any release of this extension available yet? Couldn't find it on vscode marketplace.

**Comment by FabianLauer** [comment]
You're right, it's not on the marketplace. You can try to build with `make all`. The rest of the development workflow is the same as [for other extensions](https://code.visualstudio.com/docs/extensions/overview), so you *might* be able to run by pressing <kbd>F5</kbd> in VS Code.
Since this project has been on hold for quite a while, I wouldn't be surprised if things are broken.

**Comment by AgrawalAmey** [comment]
Thanks, the build seems to be broken.

**Comment by FabianLauer** [comment]
You're welcome, sorry for the broken build. If you happen to find a fix, PRs are very welcome :wink:

**Comment by FabianLauer** [comment]
@AgrawalAmey I found some time to try and do a build. This is how I got it working:

1. pull latest version from `master`
2. `npm i coffee browserify -g`
3. `npm run-script compile`
4. VS Code debug panel → :arrow_forward: `Launch Extension`
5. in the new VS Code instance: <kbd>F1</kbd> > `Open Web Browser (Split View)`

**Comment by FabianLauer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/gBEu18ez/1-test)

**Comment by ScorpioCoding** [comment]
Making a trello board cool...

**Comment by FabianLauer** [comment]
What the heck, sorry about the noise guys.
