### ISSUE TITLE
Question: How can I install this plugin in vs-code?

### ISSUE THREAD

**Issue by TheTechOddBug** [FabianLauer/chrome-vs-code#2]
The title is the summary of the issue :)

**Comment by FabianLauer** [comment]
There's 2 ways. Either, [run it in development mode](https://github.com/FabianLauer/chrome-vs-code/issues/1#issuecomment-333107087) or build it using [`vsce package`](https://code.visualstudio.com/docs/extensions/publish-extension#_packaging-extensions).

Not sure though if this works since the project is on hold :thinking:

**Comment by TheTechOddBug** [comment]
Thanks!!

**Comment by FabianLauer** [comment]
Welcome :slightly_smiling_face:

**Comment by vinhjaxt** [comment]
Another simple way to do this, run: `code --install-extension <.vsix file>` works on windows 7

**Comment by FabianLauer** [comment]
@vinhjaxt Yup, should work on every OS: https://stackoverflow.com/a/34339780/3861083
